<!DOCTYPE html>
<html lang="en">
<head>
    <?php require_once "../../components/head.php";?>
    <title>PHY Module Documentation</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
        }

        .container {
            max-width: 1000px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        h1 {
            font-size: 2.5rem;
            font-weight: bold;
            margin-bottom: 30px;
            color: #333;
        }

        h2 {
            font-size: 1.5rem;
            font-weight: bold;
            margin: 30px 0 20px 0;
            color: #333;
        }

        .intro {
            margin-bottom: 40px;
        }

        .intro p {
            margin-bottom: 15px;
            font-size: 1rem;
            line-height: 1.6;
        }

        .fpga-section {
            margin-bottom: 40px;
            border: 1px solid #ddd;
            padding: 25px;
            background: #fafafa;
        }

        .fpga-title {
            font-size: 1.2rem;
            font-weight: bold;
            margin-bottom: 15px;
            color: #333;
        }

        .fpga-details {
            margin-bottom: 20px;
        }

        .fpga-details p {
            margin: 5px 0;
            font-size: 0.95rem;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            background: white;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border: 1px solid #ddd;
        }

        th {
            background-color: #f8f8f8;
            font-weight: bold;
            color: #333;
        }

        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tbody tr:hover {
            background-color: #f0f0f0;
        }

        .note {
            background: #f8f9fa;
            padding: 15px;
            border-left: 4px solid #333;
            margin: 20px 0;
            font-style: italic;
        }

        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }
            
            h1 {
                font-size: 2rem;
            }
            
            table {
                font-size: 0.9rem;
            }
            
            th, td {
                padding: 8px;
            }
        }
    </style>
</head>
<body>
    <?php require_once "../../components/header.php";;?>
    <div class="container">
        <h1>PHY</h1>
        
        <div class="intro">
            <p>The PHY module incorporates the high-speed transceivers (SerDes), which are external to the DP IP-cores.</p>
            <p>This module is generated by the transceiver wizard within the FPGA tool. The DisplayPort reference design comes with a PHY driver.</p>
            <p>The driver is responsible to configure the SerDes. Below is an overview of the driver configuration for each FPGA architecture.</p>
            <p>This configuration is easily modifiable to meet specific design requirements. The reference clocks are generated by the Tentiva GT clock generator.</p>
        </div>

        <div class="fpga-section">
            <div class="fpga-title">AMD UltraScale(+)</div>
            <div class="fpga-details">
                <p><strong>Serdes:</strong> GTH</p>
                <p><strong>Transmitter PLL:</strong> CPLL</p>
                <p><strong>Receiver PLL:</strong> QPLL0</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>LineRate (Gbps)</th>
                        <th>TX Reference Clock (MHz)</th>
                        <th>RX Reference Clock (MHz)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>RBR (1.6)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                    <tr>
                        <td>HBR (2.7)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                    <tr>
                        <td>HBR2 (5.4)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                    <tr>
                        <td>HBR3 (8.1)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="fpga-section">
            <div class="fpga-title">AMD Artix-7</div>
            <div class="fpga-details">
                <p><strong>Serdes:</strong> GTP</p>
                <p><strong>Transmitter PLL:</strong> PLL0</p>
                <p><strong>Receiver PLL:</strong> PLL1</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>LineRate (Gbps)</th>
                        <th>TX Reference Clock (MHz)</th>
                        <th>RX Reference Clock (MHz)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>RBR (1.6)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR (2.7)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR2 (5.4)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="fpga-section">
            <div class="fpga-title">Intel Cyclone 10 GX</div>
            <div class="fpga-details">
                <p><strong>Transmitter PLL:</strong> ATX PLL</p>
                <p><strong>Receiver PLL:</strong> Channel PLL</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>LineRate (Gbps)</th>
                        <th>TX Reference Clock (MHz)</th>
                        <th>RX Reference Clock (MHz)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>RBR (1.6)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR (2.7)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR2 (5.4)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="fpga-section">
            <div class="fpga-title">Intel Arria 10 GX</div>
            <div class="fpga-details">
                <p><strong>Transmitter PLL:</strong> ATX PLL</p>
                <p><strong>Receiver PLL:</strong> Channel PLL</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>LineRate (Gbps)</th>
                        <th>TX Reference Clock (MHz)</th>
                        <th>RX Reference Clock (MHz)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>RBR (1.6)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR (2.7)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR2 (5.4)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR3 (8.1)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="fpga-section">
            <div class="fpga-title">Lattice CertusPro-NX</div>
            <div class="fpga-details">
                <p><strong>Transmitter PLL:</strong> Tx PLL</p>
                <p><strong>Receiver PLL:</strong> CDR PLL</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>LineRate (Gbps)</th>
                        <th>TX Reference Clock (MHz)</th>
                        <th>RX Reference Clock (MHz)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>RBR (1.6)</td>
                        <td>81</td>
                        <td>81</td>
                    </tr>
                    <tr>
                        <td>HBR (2.7)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                    <tr>
                        <td>HBR2 (5.4)</td>
                        <td>135</td>
                        <td>135</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>