<!DOCTYPE html>
<html lang="en">
<head>
    <script>
        <i class="fa-solid fa-cloud-bolt"></i>
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../css/style.css">
    <title>PHY</title>
</head>
<body>
    <header>
        <?php
            require_once "../../a_elementen.php";
        ?>
        <div class="py">
            <div class="wrapper">
                <h1>PHY</h1>
                <p>The PHY module incorporates the high-speed transceivers (SerDes), which are external to the DP IP-cores.</p>
                <p>This module is generated by the transceiver wizard within the FPGA tool. The DisplayPort reference design comes with a PHY driver.</p>
                <p>The driver is responsible to configure the SerDes. Below is an overview of the driver configuration for each FPGA architecture.</p>
                <p>This configuration is easily modifiable to meet specific design requirements. The reference clocks are generated by the Tentiva GT clock generator.</p>
            </div>
        </div>
        <div class="amd">
            <div class="wrapper">
                <h4>AMD UltraScale(+)</h4>
                <h4>Serdes: GTH</h4>
                <h4>Transmitter PLL: CPLL</h4>
                <h4>Receiver PLL: QPLL0</h4>
            </div>
        </div>
        <div class="table-container4">
            <div class="wrapper">
                <table class="line-rate-table">
                <thead>
                    <tr>
                        <th>LineRate (Gbps)</th>
                        <th>TX Reference Clock (MHz)</th>
                        <th>RX Reference Clock (MHz)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>RBR (1.6)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                    <tr>
                        <td>HBR (2.7)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                    <tr>
                        <td>HBR2 (5.4)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                    <tr>
                        <td>HBR3 (8.1)</td>
                        <td>270</td>
                        <td>270</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="amd">
        <div class="wrapper">
            <h4>AMD Artix-7</h4>
            <p>Serdes: GTP</p>
            <p>Transmitter PLL: PLL0</p>
            <p>Receiver PLL: PLL1</p>
        </div>
        </div>
        <div class="table-container5">
            <div class="wrapper">
                <table class="line-rate-table">
                    <thead>
                        <tr>
                            <th>LineRate (Gbps)</th>
                            <th>TX Reference Clock (MHz)</th>
                            <th>RX Reference Clock (MHz)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>RBR (1.6)</td>
                            <td>135</td>
                            <td>135</td>
                        </tr>
                        <tr>
                            <td>HBR (2.7)</td>
                            <td>135</td>
                            <td>135</td>
                        </tr>
                        <tr>
                            <td>HBR2 (5.4)</td>
                            <td>135</td>
                            <td>135</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
  
            
    </header>
    <main>
        <div class="amd">
            <div class="wrapper">
                <h4>Intel Cyclone 10 GX</h4>
                <p>Transmitter PLL: ATX PLL</p>
                <p>Receiver PLL: Channel PLL</p>
            </div>
        </div>
        <div class="table-container6">
            <div class="wrapper">
                <table class="line-rate-table">
                    <thead>
                        <tr>
                            <th>LineRate (Gbps)</th>
                            <th>TX Reference Clock (MHz)</th>
                            <th>RX Reference Clock (MHz)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>RBR (1.6)</td>
                            <td>135</td>
                            <td>135</td>
                        </tr>
                        <tr>
                            <td>HBR (2.7)</td>
                            <td>135</td>
                            <td>135</td>
                        </tr>
                        <tr>
                            <td>HBR2 (5.4)</td>
                            <td>135</td>
                            <td>135</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="intel">
            <div class="table-container5">
                <div class="wrapper">
                    <h4>Intel Arria 10 GX</h4>
                    <p>Transmitter PLL: ATX PLL</p>
                    <p>Receiver PLL: Channel PLL</p>
                    <table class="line-rate-table">
                        <thead>
                            <tr>
                                <th>LineRate (Gbps)</th>
                                <th>TX Reference Clock (MHz)</th>
                                <th>RX Reference Clock (MHz)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>RBR (1.6)</td>
                                <td>135</td>
                                <td>135</td>
                            </tr>
                            <tr>
                                <td>HBR (2.7)</td>
                                <td>135</td>
                                <td>135</td>
                            </tr>
                            <tr>
                                <td>HBR2 (5.4)</td>
                                <td>135</td>
                                <td>135</td>
                            </tr>
                            <tr>
                                <td>HBR3 (8.1)</td>
                                <td>135</td>
                                <td>135</td>
                            </tr>
                        </tbody>
                    </table>
                </div>   
            </div>
        </div>
        <div class="lattice">
            <div class="table-container5">
                <div class="wrapper">
                    <h4>Lattice CertusPro-NX</h4>
                    <p>Transmitter PLL: Tx PLL</p>
                    <p>Receiver PLL: CDR PLL</p>
                    <table class="line-rate-table">
                        <thead>
                            <tr>
                                <th>LineRate (Gbps)</th>
                                <th>TX Reference Clock (MHz)</th>
                                <th>RX Reference Clock (MHz)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>RBR (1.6)</td>
                                <td>81</td>
                                <td>81</td>
                            </tr>
                            <tr>
                                <td>HBR (2.7)</td>
                                <td>135</td>
                                <td>135</td>
                            </tr>
                            <tr>
                                <td>HBR2 (5.4)</td>
                                <td>135</td>
                                <td>135</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
       
    
</body>
</html>